# Generated by Django 2.1.1 on 2018-10-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0002_auto_20181003_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cert',
            old_name='name',
            new_name='title',
        ),
    ]
